from pathlib import Path

path = Path('p601229_AgroBusiness_MW.sql')
text = path.read_text(encoding='utf-8')

farming_rows = [
(1,1,'Land Preparation','Prepare a fine seedbed on contour ridges before the first effective rains; incorporate well-rotted manure or compost and keep crop residues as mulch where termites are not a problem.','Konzani munda ndi mizere yotsatira mapiri mvula yoyamba isanagwe bwino; sakanizani manyowa okhwima kapena kompositi ndipo siyani zotsalira za mbewu ngati mulch ngati chiswe sichili vuto.'),
(2,1,'Planting','Plant clean maize seed at 75cm between rows and 25cm between stations, one seed per station, then gap-fill within 10 days after emergence.','Bzalani mbewu ya chimanga yabwino pa 75cm pakati pa mizere ndi 25cm pakati pa mabowo, mbewu imodzi pa bowo, ndipo bwezerani pomwe sizinamera pasanathe masiku 10.'),
(3,1,'Soil Fertility','Apply basal fertilizer or manure at planting and top-dress with nitrogen when maize is knee-high; split top-dressing if rains are heavy to reduce leaching.','Ikani feteleza woyambira kapena manyowa pobzala ndipo onjezerani nayitrojeni chimanga chikafika pa bondo; gawani top dressing ngati mvula ndi yambiri kuti isachoke m_nthaka.'),
(4,1,'Water Management','Conserve moisture with timely weeding, tied ridges in dry areas, and drainage channels in waterlogged fields.','Sungani chinyezi ndi kupalira pa nthawi yake, kupanga mizere yotsekera madzi kumadera ouma, ndi ngalande zotulutsa madzi kuminda yonyowa kwambiri.'),
(5,1,'Harvesting and Storage','Harvest when husks are dry and grain is hard, dry cobs thoroughly, shell cleanly, and store grain in hermetic bags to prevent weevils and mould.','Kololani makoko akauma ndipo njere zikakhala zolimba, yanikani makoko bwino, sulani mwaukhondo, ndipo sungani mu matumba osalowa mpweya kuti mupewe nyongolotsi ndi nkhungu.'),
(6,2,'Nursery Management','Raise tobacco seedlings on clean raised beds with sterilized soil, reliable water, and light shade; harden seedlings before transplanting.','Kwezani mbande za fodya pa mabedi okwezeka a nthaka yoyera, madzi okwanira, ndi mthunzi wochepa; zolowetsani ku dzuwa pang_ono musanazibzale.'),
(7,2,'Transplanting','Transplant vigorous seedlings after good rains into moist soil, keeping uniform spacing and replacing weak plants within the first week.','Bzalani mbande zamphamvu mvula ikagwa bwino m_nthaka yonyowa, sungani mtunda wofanana ndipo bwezerani zofooka mkati mwa sabata yoyamba.'),
(8,2,'Nutrient Management','Use soil-test guidance where available; avoid excess nitrogen late in the season because it reduces leaf quality and curing performance.','Gwiritsani malangizo a kuyezetsa nthaka ngati alipo; pewani nayitrojeni wambiri kumapeto kwa nyengo chifukwa umachepetsa khalidwe la masamba ndi kuyanika kwake.'),
(9,2,'Curing','Harvest leaves by maturity stage and cure slowly with good air movement to keep colour, aroma, and leaf body.','Kololani masamba malinga ndi kukhwima kwake ndipo yanikani pang_ono ndi mpweya wabwino kuti musunge mtundu, fungo, ndi mphamvu ya tsamba.'),
(10,2,'Rotation','Rotate tobacco with legumes or cereals and keep a break from tobacco-family crops to reduce nematodes, bacterial wilt, and soil fatigue.','Sinthanitsani fodya ndi nyemba kapena chimanga ndipo musabwereze mbewu za banja la fodya pafupi kuti muchepetse nematodes, wilt, ndi kutopa kwa nthaka.'),
(11,3,'Land Preparation','Plant groundnuts on well-drained sandy loam; make ridges early and avoid compacted or waterlogged soils that cause poor pegging.','Bzalani nthowa m_nthaka ya mchenga yosunga koma kutulutsa madzi bwino; pangani mizere msanga ndipo pewani nthaka yolimba kapena yodzaza madzi yomwe imalepheretsa mapegi.'),
(12,3,'Seed Selection','Use mature, undamaged seed treated with recommended inoculant or dressing where available; do not plant shrivelled or mouldy kernels.','Gwiritsani mbewu zokhwima komanso zosawonongeka, zokutidwa ndi inoculant kapena mankhwala ovomerezeka ngati alipo; musabzale nthowa zofota kapena za nkhungu.'),
(13,3,'Weeding','Weed early and shallow before flowering, then avoid disturbing pegs once pods start forming.','Palirani msanga komanso mozama pang_ono musanayambe maluwa, kenako pewani kusokoneza mapegi akayamba kupanga makoko.'),
(14,3,'Harvesting','Lift plants when inner shells show dark veining and most pods are filled; dry on racks or clean mats to protect quality.','Kololani zomera pamene mkati mwa makoko muli mizere yakuda ndipo makoko ambiri adzaza; yanikani pa nsanja kapena mphasa zoyera kuti khalidwe lisawonongeke.'),
(15,3,'Aflatoxin Prevention','Dry pods quickly to safe moisture, sort out damaged kernels, and store off the floor in a dry ventilated room.','Yanikani makoko mwachangu mpaka chinyezi chitetezeka, sankhani ndi kuchotsa zosweka, ndipo sungani pamwamba osati pansi m_chipinda chowuma chokhala ndi mpweya.'),
(16,4,'Inoculation','Inoculate soybean seed with the correct rhizobium if the field has not grown soybeans recently; plant immediately after inoculation.','Sakanizani mbewu ya soya ndi rhizobium yoyenera ngati mundawo sunalimidwe soya posachedwa; bzalanipo nthawi yomweyo mukatha kusakaniza.'),
(17,4,'Planting','Plant soybeans in moist, well-drained loam at uniform depth and spacing to close the canopy quickly and suppress weeds.','Bzalani soya m_nthaka yonyowa koma yotulutsa madzi bwino pa kuya ndi mtunda wofanana kuti masamba atseke msanga ndi kuchepetsa udzu.'),
(18,4,'Weed Control','Keep the field weed-free for the first 6 weeks; late weeding after flowering can damage roots and pods.','Sungani munda wopanda udzu kwa masabata 6 oyambirira; kupalira mochedwa maluwa atayamba kungawononge mizu ndi makoko.'),
(19,4,'Harvesting','Harvest when most pods are brown and seeds rattle, then dry and thresh gently to avoid splitting grain.','Kololani makoko ambiri akakhala bulauni ndipo mbewu zikamveka kugunda, kenako yanikani ndi kupuntha mosamala kuti zisagawike.'),
(20,4,'Storage','Store dry soybeans in clean bags on pallets and monitor for moisture migration during cool nights.','Sungani soya wouma mu matumba oyera pamapallet ndipo yang_anirani chinyezi makamaka usiku wozizira.'),
(21,5,'Nursery and Transplanting','Use healthy rice seedlings 18-25 days old; transplant 2-3 seedlings per hill in straight lines for easier weeding and water control.','Gwiritsani mbande za mpunga zathanzi za masiku 18-25; bzalani mbande 2-3 pa malo m_mizere yolunjika kuti kupalira ndi kusamalira madzi zikhale zosavuta.'),
(22,5,'Water Management','Keep shallow water during establishment, drain briefly for weeding and tillering, then avoid deep stagnant water except where needed for weed suppression.','Sungani madzi ochepa poyamba, tulutsani pang_ono popalira ndi kulimbikitsa nthambi, ndipo pewani madzi akuya osayenda kupatula ngati akufunika kuchepetsa udzu.'),
(23,5,'Fertility','Apply nitrogen in splits and include organic matter; yellowing after flooding often signals nitrogen loss.','Ikani nayitrojeni mogawagawana ndipo onjezani zinthu zachilengedwe; kusanduka chikasu pambuyo pa madzi ambiri nthawi zambiri kumasonyeza kutayika kwa nayitrojeni.'),
(24,5,'Harvesting','Harvest rice when 80-85% of grains are straw-coloured, then dry paddy to about 14% moisture before milling.','Kololani mpunga pamene 80-85% ya njere zasanduka mtundu wa udzu, kenako yanikani mpaka chinyezi cha pafupifupi 14% musanagaye.'),
(25,5,'Postharvest','Thresh on clean surfaces, winnow carefully, and store paddy away from moisture, rodents, and poultry.','Punthani pa malo oyera, pepetani mosamala, ndipo sungani mpunga kutali ndi chinyezi, mbewa, ndi nkhuku.'),
(26,6,'Planting','Plant cotton after reliable rains in warm soil; use recommended spacing and avoid late planting that exposes bolls to peak pests.','Bzalani kotoni mvula ikakhazikika m_nthaka yotentha; gwiritsani mtunda wovomerezeka ndipo pewani kubzala mochedwa komwe kumawonjezera tizilombo pa mabola.'),
(27,6,'Canopy Management','Thin weak plants early and keep rows open enough for scouting, spraying, and air movement.','Chepetsani zomera zofooka msanga ndipo sungani mizere yotseguka kuti kuyendera, kupopera, ndi mpweya ziziyenda bwino.'),
(28,6,'Nutrient Management','Balance nitrogen with potassium and organic matter; too much nitrogen delays boll opening and attracts sucking pests.','Yanjanitsani nayitrojeni ndi potaziyamu komanso manyowa; nayitrojeni wambiri umachedwetsa kutseguka kwa mabola ndi kukopa tizilombo toyamwa.'),
(29,6,'Picking','Pick only fully opened clean bolls, keep cotton off the soil, and separate stained or pest-damaged lint.','Kololani mabola otseguka bwino komanso oyera, musayike kotoni pansi, ndipo patulani yomwe yadetsedwa kapena yawonongeka ndi tizilombo.'),
(30,6,'Residue Management','Destroy stalks after final picking to break bollworm and stainer life cycles.','Wonongani zitsinde mukamaliza kukolola kuti mudule moyo wa bollworm ndi tizilombo todetsa kotoni.'),
(31,7,'Pruning','Prune tea to maintain a broad plucking table and remove dead wood; time pruning to avoid long dry spells.','Dulirani tiyi kuti pamwamba pa kukolola pakhale patambalala ndipo chotsani nthambi zakufa; chitani izi osati nthawi ya chilala chotalika.'),
(32,7,'Plucking','Pluck two leaves and a bud at regular intervals; coarse plucking lowers made-tea quality.','Kololani masamba awiri ndi nsonga nthawi zonse; kukolola masamba akuluakulu kumachepetsa khalidwe la tiyi.'),
(33,7,'Soil Cover','Maintain mulch and contour drains on slopes to reduce erosion and conserve moisture.','Sungani mulch ndi ngalande zotsatira mapiri kuti muchepetse kukokoloka kwa nthaka ndi kusunga chinyezi.'),
(34,7,'Fertility','Apply fertilizer after rainfall when bushes are actively growing and keep it away from stems to avoid scorch.','Ikani feteleza mvula ikagwa pamene tiyi ukukula bwino ndipo musayiyike pafupi ndi tsinde kuti isawotche.'),
(35,7,'Quality Handling','Keep plucked leaf shaded, loose, and delivered quickly to prevent heating and fermentation before processing.','Sungani masamba okolola pa mthunzi, osakanikizana kwambiri, ndipo aperekedwe mwachangu kuti asatenthe kapena kufementa asanapangidwe.'),
(36,8,'Shade Management','Maintain balanced shade in coffee: enough to reduce heat stress, but open enough for airflow and flowering.','Sungani mthunzi woyenera pa kofi: wokwanira kuchepetsa kutentha koma wotseguka kuti mpweya ndi maluwa ziyende bwino.'),
(37,8,'Pruning','Remove suckers, dead wood, and crossing branches after harvest to keep a productive open frame.','Chotsani nthambi zophukira pansi, zakufa, ndi zopingasa mukatha kukolola kuti mtengo ukhale wotseguka ndi wobala bwino.'),
(38,8,'Nutrition','Feed coffee with compost plus balanced fertilizer at the start of rains and during berry development.','Dyetsani kofi ndi kompositi kuphatikiza feteleza woyenera koyambirira kwa mvula ndi nthawi imene zipatso zikukula.'),
(39,8,'Harvesting','Pick only ripe red cherries in rounds; mixing green, black, and red cherries reduces cup quality.','Kololani zipatso zofiira zokha mobwerezabwereza; kusakaniza zobiriwira, zakuda, ndi zofiira kumachepetsa khalidwe la kofi.'),
(40,8,'Processing','Pulp the same day, ferment only until mucilage loosens, wash clean, and dry slowly on raised beds.','Pangani pulping tsiku lomwelo, fermentani mpaka mucilage itamasuka, sambani bwino, ndipo yanikani pang_ono pa mabedi okwezeka.'),
(41,9,'Planting','Plant beans in well-drained soil after the first good rains; avoid fields with recent bean root rot or heavy waterlogging.','Bzalani nyemba m_nthaka yotulutsa madzi bwino mvula yabwino yoyamba ikagwa; pewani minda yomwe yakhala ndi matenda a mizu kapena madzi ambiri.'),
(42,9,'Seed Health','Use clean seed and dress or inoculate where recommended; do not recycle seed from diseased plants.','Gwiritsani mbewu yoyera ndipo ikani mankhwala kapena inoculant ngati zikulimbikitsidwa; musagwiritse mbewu kuchokera ku zomera zodwala.'),
(43,9,'Moisture Management','Beans need moisture at flowering and pod fill; mulch lightly and avoid overhead irrigation late in the day to reduce leaf diseases.','Nyemba zimafuna chinyezi pa maluwa ndi kudzaza makoko; ikani mulch pang_ono ndipo pewani kuthirira pamwamba mochedwa kuti muchepetse matenda a masamba.'),
(44,9,'Harvesting','Harvest when pods are dry but before shattering, then dry on tarpaulins or raised mats.','Kololani makoko akauma koma asanaphwanye, kenako yanikani pa matenti kapena mphasa zokwezeka.'),
(45,9,'Storage','Dry beans thoroughly, sort out damaged seed, and store in hermetic bags or clean sealed containers.','Yanikani nyemba bwino, chotsani zowonongeka, ndipo sungani mu matumba osalowa mpweya kapena ziwiya zoyera zotsekedwa.'),
]

pest_rows = [
(1,1,1,'Scout maize twice a week from emergence to tasselling; crush fall armyworm egg masses and apply recommended control only when many whorls show fresh damage.','Yang_anani chimanga kawiri pa sabata kuchokera kumera mpaka kutulutsa nthenga; phwanyani mazira a fall armyworm ndipo gwiritsani mankhwala ovomerezeka pokhapokha masamba ambiri awonetsa kuwonongeka kwatsopano.'),
(2,2,2,'For tobacco, rotate nursery sites, sterilize seedbed soil, and remove seedlings with damping-off or viral symptoms immediately.','Pa fodya, sinthanitsani malo a nazale, yeretsani nthaka ya mabedi, ndipo chotsani mbande zokhala ndi damping-off kapena zizindikiro za virus nthawi yomweyo.'),
(3,3,3,'Reduce groundnut aphids and rosette by planting early, removing volunteer groundnuts, and controlling aphids before leaves curl.','Chepetsani nsabwe ndi rosette pa nthowa pobzala msanga, kuchotsa nthowa zongomera zokha, ndi kulamulira nsabwe masamba asanakungike.'),
(4,1,4,'Use push-pull where possible: plant Desmodium between maize rows and Napier or Brachiaria around the field to reduce stemborers and fall armyworm pressure.','Gwiritsani push-pull ngati n_kotheka: bzalani Desmodium pakati pa mizere ya chimanga ndi Napier kapena Brachiaria mozungulira munda kuti muchepetse stemborer ndi fall armyworm.'),
(5,1,5,'Keep maize fields weed-free during the first 6 weeks; grassy weeds host stemborers and make armyworm scouting difficult.','Sungani munda wa chimanga wopanda udzu kwa masabata 6 oyambirira; udzu wa grass umasunga stemborer ndipo umapangitsa kuyendera armyworm kukhala kovuta.'),
(6,1,6,'After harvest, destroy heavily infested maize stalks and rotate with legumes to break stemborer carry-over.','Mukatha kukolola, wonongani zitsinde za chimanga zomwe zawonongeka kwambiri ndipo sinthanitsani ndi nyemba kuti mudule moyo wa stemborer.'),
(7,2,7,'Handpick tobacco hornworms during morning scouting and conserve beneficial wasps by avoiding unnecessary broad-spectrum sprays.','Tolaninso hornworm pa fodya mukayendera m_mawa ndipo sungani tizilombo tothandiza popewa kupopera mankhwala amphamvu osafunikira.'),
(8,3,8,'Store groundnuts only when fully dry; use hermetic bags and inspect monthly for bruchids, mould, or aflatoxin risk.','Sungani nthowa zikakhala zouma bwino; gwiritsani matumba osalowa mpweya ndipo yang_anani mwezi uliwonse pa bruchids, nkhungu, kapena chiopsezo cha aflatoxin.'),
(9,6,9,'Install pheromone traps and scout cotton squares weekly; treat bollworms based on threshold, not calendar spraying.','Ikani ma pheromone trap ndipo yang_anani mabatani a kotoni sabata iliyonse; lamulirani bollworm malinga ndi kuchuluka kwake osati kungopopera pa kalendala.'),
(10,5,10,'For rice stem borers, remove rice stubble after harvest, synchronize planting with neighbours, and avoid excess nitrogen.','Pa stem borer wa mpunga, chotsani zitsinde za mpunga mukakolola, bzalani nthawi yofanana ndi oyandikana nawo, ndipo pewani nayitrojeni wambiri.'),
(11,7,11,'Manage tea mosquito bug by pruning for airflow, removing badly damaged shoots, and using targeted sprays only on active hotspots.','Lamulirani tea mosquito bug podulira kuti mpweya uyende, kuchotsa mphukira zowonongeka kwambiri, ndi kupopera malo omwe ali ndi vuto lokha.'),
(12,8,12,'Control coffee leaf rust with open pruning, balanced nutrition, removal of infected leaves, and timely copper or approved fungicide before long wet periods.','Lamulirani rust ya kofi ndi kudulira kotsegula, zakudya zoyenera, kuchotsa masamba odwala, ndi copper kapena fungicide yovomerezeka mvula yaitali isanayambe.'),
(13,6,13,'Reduce cotton jassids and aphids by avoiding drought stress, conserving ladybirds, and spraying only when underside leaf counts exceed threshold.','Chepetsani jassid ndi nsabwe pa kotoni popewa chilala pa zomera, kusunga ladybird, ndi kupopera pokhapokha kuchuluka pansi pa masamba kwapitirira malire.'),
(14,5,14,'In lowland rice, keep bunds clean and use alternate wetting and drying to reduce weeds, snails, and disease pressure.','Mu mpunga wa m_madambo, yeretsani malire a minda ndipo sinthanitsani kuthirira ndi kuumitsa kuti muchepetse udzu, nkhono, ndi matenda.'),
(15,9,15,'Prevent bean bruchids by drying grain well, freezing or solar-heating small seed lots where practical, then sealing in hermetic storage.','Pewani bruchid wa nyemba poumitsa bwino, kuziziritsa kapena kutenthetsa ndi dzuwa mbewu zochepa ngati n_kotheka, kenako kusunga mosalowa mpweya.'),
(16,4,16,'Scout soybeans for rust and frogeye leaf spot from flowering; improve airflow and apply approved fungicide early when disease is first seen.','Yang_anani soya pa rust ndi frogeye kuyambira maluwa; limbikitsani mpweya ndipo ikani fungicide yovomerezeka matenda akangoyamba kuoneka.'),
(17,9,17,'Reduce bean root rot by rotating for at least two seasons, planting on ridges, and avoiding poorly drained fields.','Chepetsani matenda a mizu ya nyemba posinthanitsa mbewu kwa nyengo ziwiri kapena kuposerapo, kubzala pa mizere, ndi kupewa minda yosatulutsa madzi.'),
(18,4,18,'Use yellow sticky traps and early scouting for soybean aphids and whiteflies; protect natural enemies before choosing sprays.','Gwiritsani ma trap achikasu ndi kuyendera msanga pa nsabwe ndi whitefly za soya; tetezani tizilombo tothandiza musanasankhe kupopera.'),
(19,7,19,'For tea red spider mite, reduce dust, avoid water stress, prune old infested foliage, and spot-treat only affected blocks.','Pa red spider mite wa tiyi, chepetsani fumbi, pewani kusowa madzi, dulani masamba akale owonongeka, ndipo perekani mankhwala pa malo omwe ali ndi vuto lokha.'),
(20,3,20,'For groundnut leaf spots, rotate crops, use clean seed, avoid overhead watering late in the day, and apply approved fungicide when early spots appear.','Pa leaf spot ya nthowa, sinthanitsani mbewu, gwiritsani mbewu yoyera, pewani kuthirira pamwamba madzulo, ndipo ikani fungicide yovomerezeka zizindikiro zikangoyamba.'),
(21,1,21,'Protect stored maize with hermetic PICS-style bags or clean sealed drums; dry grain thoroughly and never mix new grain with infested old grain.','Tetezani chimanga chosungidwa ndi matumba a PICS kapena migolo yoyera yotsekedwa; yanikani njere bwino ndipo musasakanize chatsopano ndi chakale chokhala ndi tizilombo.'),
(22,2,22,'Remove and bury or compost tobacco residues after harvest; volunteer plants carry aphids, whiteflies, and viral diseases into the next crop.','Chotsani ndi kukwirira kapena kupanga kompositi zotsalira za fodya mukatha kukolola; zomera zongomera zimasunga nsabwe, whitefly, ndi matenda a virus ku nyengo yotsatira.'),
(23,6,23,'Use light traps only as monitoring aids for cotton moths; combine with field scouting so beneficial insects are not harmed unnecessarily.','Gwiritsani ma light trap ngati chida choyang_anira moth wa kotoni; phatikizani ndi kuyendera munda kuti tizilombo tothandiza tisawonongeke mosafunikira.'),
(24,5,24,'Reduce rice blast by planting tolerant varieties, using clean seed, avoiding dense planting, and keeping nitrogen balanced.','Chepetsani rice blast pobzala mitundu yopirira, kugwiritsa mbewu yoyera, kupewa kubzala mopanikizana, ndi kusunga nayitrojeni moyenera.'),
(25,8,27,'Control coffee berry disease by harvesting all ripe and dried berries, pruning for sunlight, and applying approved protectant before wet spells.','Lamulirani matenda a zipatso za kofi pokolola zipatso zonse zokhwima ndi zouma, kudulira kuti dzuwa lilowe, ndi kugwiritsa mankhwala oteteza mvula isanayambe.'),
(26,9,6,'In horticultural-style bean plots, use raised beds, drip or furrow irrigation, and morning watering to reduce angular leaf spot and anthracnose.','M_minda ya nyemba ngati horticulture, gwiritsani mabedi okwezeka, kuthirira pa mizere kapena drip, ndi kuthirira m_mawa kuti muchepetse angular leaf spot ndi anthracnose.'),
(27,4,7,'Rotate soybeans with cereals and avoid repeated soybean fields to reduce soybean cyst nematode, root rots, and soil-borne diseases.','Sinthanitsani soya ndi chimanga ndipo pewani kubwereza soya pamunda womwewo kuti muchepetse nematode, matenda a mizu, ndi matenda a m_nthaka.'),
(28,3,18,'Use field sanitation against rodents in groundnut: clear hiding places, harvest promptly, and store pods off the floor.','Gwiritsani ukhondo wa munda polimbana ndi mbewa pa nthowa: chotsani malo obisalira, kololani pa nthawi yake, ndipo sungani makoko pamwamba osati pansi.'),
(29,7,25,'In tea nurseries, prevent damping-off with sterile rooting media, raised benches, good drainage, and careful watering.','Mu nazale za tiyi, pewani damping-off ndi media yoyera, mabenchi okwezeka, madzi otuluka bwino, ndi kuthirira mosamala.'),
(30,8,26,'For coffee berry borer, collect fallen berries, strip leftover berries after harvest, and use alcohol-baited traps for monitoring.','Pa coffee berry borer, sonkhanitsani zipatso zagwa, chotsani zotsala mukatha kukolola, ndipo gwiritsani ma trap okhala ndi alcohol poyang_anira.'),
]

def esc(v):
    return str(v).replace('\\','\\\\').replace("'","''")

def insert_sql(table, cols, rows):
    lines = [f"INSERT INTO `{table}` ({', '.join('`'+c+'`' for c in cols)}) VALUES"]
    vals = []
    for row in rows:
        parts = []
        for v in row:
            parts.append(str(v) if isinstance(v, int) else f"'{esc(v)}'")
        vals.append('(' + ', '.join(parts) + ')')
    return '\n'.join(lines) + '\n' + ',\n'.join(vals) + ';'

for table, cols, rows in [
    ('farming_best_practices', ['id','crop_id','practice_type','practice_en','practice_ci'], farming_rows),
    ('pest_control_tips', ['id','crop_id','district_id','tip_en','tip_ci'], pest_rows),
]:
    start = text.index(f'INSERT INTO `{table}`')
    end = text.index('\n\n-- --------------------------------------------------------', start)
    text = text[:start] + insert_sql(table, cols, rows) + text[end:]

text = text.replace('MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;', 'MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;', 1)
text = text.replace('MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;', 'MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;', 1)
path.write_text(text, encoding='utf-8')
print(f'Updated {len(farming_rows)} farming practices and {len(pest_rows)} pest tips')
